---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections: 
upload_dir: images
public_path: "/docs/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
